### PR TITLE
feat: VSCodeVariant add windsurf

### PR DESCRIPTION
**Pull request by codeime**
vscode integrations add windsurf support

### CODE REVIEW

**Comment by grant0417** [comment]
Thanks for the contribution! You also need to add windsurf to the `fig_utils::terminal` module like Vscode/Cursor.

https://github.com/aws/amazon-q-developer-cli/blob/main/crates/fig_util/src/terminal.rs

**Comment by grant0417** [comment]
Also you can ignore the "Typos / Spell Check" failing, I have another PR (https://github.com/aws/amazon-q-developer-cli/pull/124) that will fix that soon.

**Comment by codeime** [comment]
Hi, how do i fix the Co-authored-by email. I used the incorrect email address.

**Comment by codeime** [comment]
@grant0417  Hi, how do i fix the Co-authored-by email. I used the incorrect email address.

**Pull request merged**
