### PR TITLE
fix: accept text through pipes in chat

### PR DESCRIPTION
**Pull request by Rahel-A**
For the `q chat` command, also allow piping text into the q chat command.

*Issue #, if available:*
#258 
*Description of changes:*
Similarly to `smartcat`, check if we're piping text, if so, then the chat input will be fetched from the stdin.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Rahel-A** [comment]
Tested through CLI:
```
echo "say hi" | rustup run stable-x86_64-unknown-linux-gnu cargo run -- chat
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.46s
     Running `/home/ANT.AMAZON.COM/rahelgah/work/amazon-q-developer-cli/target/debug/q_cli chat`

Hi! How can I help you with your development needs today?
```

**Comment by Rahel-A** [comment]
[27e104f](https://github.com/aws/amazon-q-developer-cli/pull/259/commits/27e104f0b4473d7802cce2068ea4bcdd4eedbfa7) works but at the end there's still some more ANSI characters.

**Comment by grant0417** [comment]
Also can you edit the description the PR to include:

> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Comment by Rahel-A** [comment]
Do you have some default prompts auto embedded for the first question?
This is the prompt used in `smartcat`:
```
                You are an extremely skilled programmer with a keen eye for detail and an emphasis on readable code. \
                You have been tasked with acting as a smart version of the cat unix program. You take text and a prompt in and write text out. \
                For that reason, it is of crucial importance to just write the desired output. Do not under any circumstance write any comment or thought \
                as your output will be piped into other programs. Do not write the markdown delimiters for code as well. \
                Sometimes you will be asked to implement or extend some input code. Same thing goes here, write only what was asked because what you write will \
                be directly added to the user's editor. \
                Never ever write ``` around the code. \
                Make sure to keep the indentation and formatting. \
```

**Review by grant0417 — APPROVED** [review]

**Pull request merged**
